---
- name: Ensure Elasticsearch is stopped
  become: yes
  service:
    name: elasticsearch
    state: stop
    enabled: true
  tags: execution

- name: Remove Elasticsearch
  become: yes
  yum:
    name: elasticsearch
    state: removed
  register: elastic_install
  until: elastic_install is succeeded
  tags: installation

- name: remove elasticsearch node data
  become: yes
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/elasticsearch
    - /etc/elasticsearch