---
- name: Check if this deployment is in single node mode
  include: mode_check.yml
  tags: configuration

- name: Install Elasticsearch version {{ elasticsearch_version }}.
  become: yes
  yum:
    name: elasticsearch-{{ elasticsearch_version }}
    state: present
  register: elastic_install
  until: elastic_install is succeeded
  tags: installation

- include: config.yml
  tags: configuration

- name: open firewall 9200/9300
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: true
  tags: configuration
  loop: 
    - 9200/tcp
    - 9300/tcp

- name: Ensure Elasticsearch is started and enabled at boot.
  become: yes
  service:
    name: elasticsearch
    state: started
    enabled: true
  tags: execution

- name: upload template and lifecycle
  block:
    - name: upload applog lifecycle
      uri:
        url: http://{{ inventory_hostname }}:9200/_ilm/policy/app_log_policy
        method: PUT
        src: templates/applog-lifecycle.json
        body_format: json

    - name: upload system-mesos-guis lifecycle
      uri:
        url: http://{{ inventory_hostname }}:9200/_ilm/policy/system_mesos_guis_policy
        method: PUT
        src: templates/system_mesos_guis-lifecycle.json
        body_format: json

    - name: upload applog template
      uri:
        url: http://{{ inventory_hostname }}:9200/_template/app_log?include_type_name
        method: PUT
        src: templates/applog-index_template.json
        body_format: json

    - name: upload system-mesos-guis template
      uri:
        url: http://{{ inventory_hostname }}:9200/_template/system_mesos_guis?include_type_name
        method: PUT
        src: templates/system_mesos_guis-index_template.json
        body_format: json
  environment:
    no_proxy: "{{ inventory_hostname }}"
  run_once: true
  tags: configuration