---

- name: Install Elasticsearch version {{ elasticsearch_version }}.
  become: yes
  yum:
    name: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch_version }}-x86_64.rpm
    state: present
  register: elastic_install
  until: elastic_install is succeeded
  tags: installation


- include: config.yml
  tags: configuration
  # when: elastic_create_config | bool

- name: Disable repo to prevent autoupdate
  command: yum-config-manager --disable  elasticsearch-7.x
  become: yes
  tags: configuration
  changed_when: false

- name: open firewall 9200
  command: firewall-cmd --add-port=9200/tcp --permanent
  become: yes
  tags: configuration
  changed_when: false

- name: open firewall 9300
  command: firewall-cmd --add-port=9300/tcp --permanent
  become: yes
  tags: configuration
  changed_when: false

- name: reload firewall
  command: firewall-cmd --reload
  become: yes
  tags: configuration
  changed_when: false

- name: upload template and lifecycle
  block:
    - name: upload lifecycle
      uri:
        url: http://{{ inventory_hostname }}:9200/_ilm/policy/app_log_policy
        method: PUT
        body: "{"policy":{"phases":{"hot":{"min_age":"0ms","actions":{"set_priority":{"priority":100}}},"delete":{"min_age":"3d","actions":{"delete":{"delete_searchable_snapshot":true}}}}}}"
        body_format: json
  run_once: true

- name: Ensure Elasticsearch is started and enabled at boot.
  become: yes
  service:
    name: elasticsearch
    state: started
    enabled: true
  tags: execution