---

- name: Install Elasticsearch version {{ elasticsearch_version }}.
  become: yes
  yum:
    name: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch_version }}-x86_64.rpm
    state: present
  register: elastic_install
  until: elastic_install is succeeded
  tags: installation


- include: config.yml
  tags: configuration
  # when: elastic_create_config | bool

- name: Disable repo to prevent autoupdate
  command: yum-config-manager --disable  elasticsearch-7.x
  become: yes
  tags: configuration
  changed_when: false

- name: open firewall 9200
  command: firewall-cmd --add-port=9200/tcp --permanent
  become: yes
  tags: configuration
  changed_when: false

- name: open firewall 9300
  command: firewall-cmd --add-port=9300/tcp --permanent
  become: yes
  tags: configuration
  changed_when: false

- name: reload firewall
  command: firewall-cmd --reload
  become: yes
  tags: configuration
  changed_when: false

- name: Ensure Elasticsearch is started and enabled at boot.
  become: yes
  service:
    name: elasticsearch
    state: started
    enabled: true
  tags: execution

- name: upload template and lifecycle
  block:
    - name: upload applog lifecycle
      uri:
        url: http://{{ inventory_hostname }}:9200/_ilm/policy/app_log_policy
        method: PUT
        body: {"policy":{"phases":{"hot":{"min_age":"0ms","actions":{"set_priority":{"priority":100}}},"delete":{"min_age":"3d","actions":{"delete":{"delete_searchable_snapshot":true}}}}}}
        body_format: json

    - name: upload system-mesos-guis lifecycle
      uri:
        url: http://{{ inventory_hostname }}:9200/_ilm/policy/system_mesos_guis_policy
        method: PUT
        body: {"policy":{"phases":{"hot":{"min_age":"0ms","actions":{"set_priority":{"priority":100}}},"delete":{"min_age":"30d","actions":{"delete":{"delete_searchable_snapshot":true}}}}}}
        body_format: json

    - name: upload applog template
      uri:
        url: http://{{ inventory_hostname }}:9200/_template/app_log?include_type_name
        method: PUT
        body: '{"order":0,"index_patterns":["app_log*"],"settings":{"index":{"lifecycle":{"name":"app_log_policy"},"number_of_shards":"3"}},"aliases":{},"mappings":{"_doc":{"_routing":{"required":false},"numeric_detection":false,"dynamic_date_formats":["strict_date_optional_time","yyyy\/MM\/dd HH:mm:ss Z||yyyy\/MM\/dd Z"],"_meta":{},"dynamic":true,"_source":{"excludes":[],"includes":[],"enabled":true},"dynamic_templates":[{"message_fields":{"path_match":"message","mapping":{"norms":false,"type":"text","fields":{"keyword":{"ignore_above":1000,"type":"keyword"}}},"match_mapping_type":"string","match":"*"}},{"string_fields":{"mapping":{"norms":false,"type":"text","fields":{"keyword":{"ignore_above":256,"type":"keyword"}}},"match_mapping_type":"string","match":"*"}}],"date_detection":true,"properties":{}}}}'
        body_format: json

    - name: upload system-mesos-guis template
      uri:
        url: http://{{ inventory_hostname }}:9200/_template/system-mesos-guis?include_type_name
        method: PUT
        body: '{"order":0,"index_patterns":["guis*","mesos*","system*"],"settings":{"index":{"lifecycle":{"name":"system_mesos_guis_policy"},"number_of_shards":"1"}},"aliases":{},"mappings":{"_doc":{"_meta":{},"_source":{},"properties":{}}}}'
        body_format: json
  run_once: true
  tags: configuration