---

- name: Check development deploy mode
  when: (groups['elasticsearch'][0] == groups['kibana'][0]) or (groups['elasticsearch'][0] == groups['logstash'][0])
  set_fact:
    elasticsearch_dev_mode: true
    elasticsearch_heap_size: "{{ (ansible_memtotal_mb/4)|int|abs }}m"