---
- name: Check single node deployment mode
  when: groups["elasticsearch"] is not defined
  set_fact:
    elasticsearch_singlenode_mode: true
    elasticsearch_heap_size: "{{ (ansible_memtotal_mb/4)|int|abs }}m"