---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Install Elasticsearch version {{ es_version }}.
  become: yes
  yum:
    name: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ es_version }}-x86_64.rpm
    state: present
  register: elastic_install
  until: elastic_install is succeeded


- include: config.yml
  # when: elastic_create_config | bool

- name: Disable repo to prevent autoupdate
  command: yum-config-manager --disable  elasticsearch-7.x
  become: yes

- name: open firewall 9200-9300
  command: firewall-cmd --add-port={9200/tcp,9300/tcp} --permanent
  become: yes

- name: reload firewall
  command: firewall-cmd --reload
  become: yes

- name: Ensure Elasticsearch is started and enabled at boot.
  become: yes
  service:
    name: elasticsearch
    state: started
    enabled: true

# - name: open firewall 9200-9300
#   become: yes
#   ansible.posix.firewalld:
#     port: 9200-9300/tcp
#     permanent: yes
#     state: enabled
#     immediate: yes