---
- hosts: elasticsearch
  become: yes
  roles:
   - role: elasticsearch
  vars:
    elasticsearch_heap_size: "2g"
  tags: elasticsearch

- hosts: logstash
  become: yes
  roles:
   - role: logstash
  vars:
    logstash_heap_size: "4g"
  tags: logstash

- hosts: kibana
  become: yes
  roles:
    - role: kibana
  tags: kibana

