---
- hosts: elasticsearch
  become: yes
  tasks:
  - uri:
      url: http://{{ inventory_hostname }}:9200/_snapshot/kmutt_elasticsearch_repo
      method: PUT
      body: 
        type: url
        settings: 
          url: "{{ elasticsearch_repo_url }}"
  vars:
    elasticsearch_repo_url: "https://vue-components-develop.s3.ap-southeast-1.amazonaws.com/elastic_snapshot_repo/"

