---
- hosts: elasticsearch
  become: yes
  roles:
   - role: elasticsearch
  vars:
    elasticsearch_heap_size: "2g"
  tags: elasticsearch

- hosts: logstash
  become: yes
  roles:
   - role: logstash
  vars:
    logstash_heap_size: "2g"
  tags: logstash

- hosts: kibana
  become: yes
  roles:
    - role: kibana
  tags: kibana

- name: restart logstash
  hosts: logstash
  become: yes
  tasks:
  - service:
      name: logstash
      state: restarted
  tags: restart-logstash
