---
- hosts: logstash
  become: yes
  roles:
   - role: logstash
  vars:
    logstash_heap_size: "2g"

# - name: restart logstash
#   hosts: logstash
#   become: yes
#   tasks:
#   - service:
#       name: logstash
#       state: restarted
#   tags: restart-logstash