---
- name: Install Kibana version {{ kibana_version }}.
  become: yes
  yum:
    name: https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-x86_64.rpm
    state: present
  register: kibana_install
  until: kibana_install is succeeded
  tags: installation

- include: config.yml
  tags: configuration

- name: Disable repo to prevent autoupdate
  command: yum-config-manager --disable  elasticsearch-7.x
  become: yes
  tags: configuration
  changed_when: false

- name: open firewall port 5601
  command: firewall-cmd --add-port=5601/tcp --permanent
  become: yes
  tags: configuration
  changed_when: false

- name: reload firewall
  command: firewall-cmd --reload
  become: yes
  tags: configuration
  changed_when: false

- name: Ensure Kibana is started and enabled at boot.
  become: yes
  service:
    name: kibana
    state: started
    enabled: true
  tags: execution

- name: Upload Kibana Dashboard
#workaround
  block:
    - name: copy dashboard file to host
      become: yes
      copy:
        src: templates/Kibana_dashboard_export_ALL.ndjson.j2
        dest: "{{ kibana_dashboard_location }}"
        owner: root
        group: kibana
        mode: "660"

    - name: copy upload command
      become: yes
      template:
        src: upload_dashboard.j2
        dest: /etc/kibana/upload_dashboard
        owner: root
        group: kibana
        mode: "755"
  tags: configuration

- name: upload dashboard
  become: yes
  shell: >
    set -o pipefail;unset http_proxy;unset https_proxy;
    sh /etc/kibana/upload_dashboard
  changed_when: false
  tags: configuration


# - name: Upload Kibana Dashboard
#   uri:
#     url: "http://{{ ansible_hostname }}:5601/api/saved_objects/_import"
#     # body_format: form-urlencoded
#     headers:
#       Content-Type: multipart/form-data; boundary=------------------ThisIsBoundary
#       kbn-xsrf: true
#     method: POST
#     src: templates/Kibana_dashboard_export_ALL.ndjson
#   tags: configuration