---
- name: Copy Logstash configuration.
  block:
    - name: logstash.yml
      become: yes
      template:
        src: logstash.yml.j2
        dest: "/etc/logstash/logstash.yml"
        owner: root
        group: logstash
        mode: "660"

    - name: jvm.options
      become: yes
      template:
        src: jvm.options.j2
        dest: "/etc/logstash/jvm.options"
        owner: root
        group: logstash
        mode: "660"

    - name: pipeline setting (pipeline.yml)
      become: yes
      template:
        src: pipelines.yml.j2
        dest: "/etc/logstash/pipelines.yml"
        owner: root
        group: logstash
        mode: "660"
  tags: configuration

- name: Copy Pipeline config
  block:
    - name: applog pipeline
      become: yes
      template:
        src: applog.conf.j2
        dest: "/etc/logstash/conf.d/applog.conf"
        owner: root
        group: logstash
        mode: "660"
      run_once: true
      delegate_to: "{{ ansible_play_hosts[0] }}"

    - name: mesos-system pipeline
      become: yes
      template:
        src: system_mesos-log.conf.j2
        dest: "/etc/logstash/conf.d/system_mesos-log.conf"
        owner: root
        group: logstash
        mode: "660"
  tags: configuration