---

- name: Check if this deployment is in development mode
  include: mode_check.yml
  tags: configuration

- rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Install Logstash version {{ logstash_version }}.
  become: yes
  yum:
    name: https://artifacts.elastic.co/downloads/logstash/logstash-{{ logstash_version }}-x86_64.rpm
    state: present
  register: logstash_install
  until: logstash_install is succeeded
  tags: installation

# jdk is now bundled in logstash 7.10+ installation
# 
# - name: Install Java
#   yum:
#     name: java-11-openjdk-devel
#     state: present
#   register: Java_install
#   until: Java_install is succeeded
#   become: yes
#   tags: installation

- name: Install mysql repository (for CS8)
  become: yes
  yum:
    name: https://dev.mysql.com/get/mysql80-community-release-el8-1.noarch.rpm
    state: present
  register: mysql_repo_install
  until: mysql_repo_install is succeeded
  tags: installation

- name: Install JDBC
  yum:
    name: mysql-connector-java
    state: present
  become: yes
  register: JDBC_install
  until: JDBC_install is succeeded
  tags: installation

- include: config.yml
  tags: configuration

# Previously used for elk 7.9.x 
# - name: Disable repo to prevent autoupdate
#   command: yum-config-manager --disable  elasticsearch-7.x
#   become: yes
#   tags: configuration
#   changed_when: false

- name: open firewall 5044
  command: firewall-cmd --add-port=5044/tcp --permanent
  become: yes
  tags: configuration
  changed_when: false

- name: reload firewall
  command: firewall-cmd --reload
  become: yes
  tags: configuration
  changed_when: false

# this task is probably not necessary for 7.10+
# as it is for fixing logstash service (~7.9) is not properly built
# if logstash was installed before java installation.
# but it will be left here, just in case the assumption is wrong.
- name: manually build logstash service for systemd
  command: /usr/share/logstash/bin/system-install
  become: yes
  tags: installation
  changed_when: false

- name: Ensure Logstash is started and enabled at boot.
  become: yes
  service:
    name: logstash
    state: started
    enabled: true
  tags: execution
