---
- name: Install Logstash version {{ logstash_version }}.
  become: yes
  yum:
    name: https://artifacts.elastic.co/downloads/logstash/logstash-{{ logstash_version }}.rpm
    state: present
  register: logstash_install
  until: logstash_install is succeeded
  tags: installation

- name: Install Java
  yum: 
    name: java-11-openjdk-devel
    state: present
  register: Java_install
  until: Java_install is succeeded
  become: yes
  tags: installation

- name: Install JDBC
  yum:
    name: mysql-connector-java
    state: present
  become: yes
  register: JDBC_install
  until: JDBC_install is succeeded
  tags: installation

- include: config.yml
  tags: configuration

- name: Disable repo to prevent autoupdate
  command: yum-config-manager --disable  elasticsearch-7.x
  become: yes
  tags: configuration
  changed_when: false

- name: open firewall 5044
  command: firewall-cmd --add-port=5044/tcp --permanent
  become: yes
  tags: configuration
  changed_when: false

- name: reload firewall
  command: firewall-cmd --reload
  become: yes
  tags: configuration
  changed_when: false

- name: Ensure Logstash is started and enabled at boot.
  become: yes
  service:
    name: logstash
    state: started
    enabled: true
  tags: execution
