---
- name: Check if this deployment is in single node mode
  include: mode_check.yml
  tags: configuration

- name: Install Logstash version {{ logstash_version }}.
  become: yes
  yum:
    name: logstash-{{ logstash_version }}
    state: present
  register: logstash_install
  until: logstash_install is succeeded
  tags: installation

- name: Install JDBC
  yum:
    name: mysql-connector-java
    state: present
  become: yes
  register: jdbc_install
  until: jdbc_install is succeeded
  tags: installation

- include: config.yml
  tags: configuration

- name: open firewall 5044
  firewalld:
    port: 5044/tcp
    permanent: yes
    state: enabled
    immediate: true
  tags: configuration

- name: Remove problematic TimeoutStopSec option from logstash systemd unit
  ansible.builtin.lineinfile:
    path: /etc/systemd/system/logstash.service
    state: absent
    line: "TimeoutStopSec=infinity"
  tags: configuration

- name: Ensure Logstash is started and enabled at boot.
  become: yes
  service:
    name: logstash
    state: started
    enabled: true
  tags: execution
