---
- name: Check development deploy mode
  when: groups["logstash"] is not defined
  set_fact:
    logstash_singlenode_mode: true
    logstash_heap_size: "{{ ((ansible_memtotal_mb*3)/20)|int|abs }}m"