---

- name: Check development deploy mode
  when: groups['elasticsearch'][0] == groups['kibana'][0] or groups['elasticsearch'][0] == groups['logstash'][0]
  set_fact:
    logstash_dev_mode: true
    logstash_heap_size: "{{ ((ansible_memtotal_mb*3)/20)|int|abs }}m"